env:
  - IP=128.199.134.167 PORT=80 DEPLOY_DIR=/usr/src/truegrail-backend
addons:
  ssh_known_hosts:
    - 128.199.134.167 (128.199.134.167)
before_script:
  - echo -e "Host 128.199.134.167\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
branches:
  only:
  - master
language: node_js
node_js: 8.10.0
before_install:
- openssl aes-256-cbc -K $encrypted_507e586d9e43_key -iv $encrypted_507e586d9e43_iv
  -in id_rsa_travis_grail.enc -out ./id_rsa_travis_grail -d
- chmod u+x deploy.sh
after_success:
  - echo $IP
  - sudo ./deploy.sh
