env:
  - IP=128.199.134.167 PORT=80 DEPLOY_DIR=/usr/src/truegrail-backend TRAVIS_SSH_KEY_TYPES=ssh-rsa
branches:
  only:
  - master
language: node_js
node_js: 8.10.0
before_install:
- ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H $IP > $TRAVIS_HOME/.ssh/known_hosts
- openssl aes-256-cbc -K $encrypted_507e586d9e43_key -iv $encrypted_507e586d9e43_iv
  -in id_rsa_travis_grail.enc -out ./id_rsa_travis_grail -d
- chmod u+x deploy.sh
after_success:
  - echo $IP
  - printf 'yes\n' | sudo ./deploy.sh
