env:
  - IP = 128.199.134.167
  - PORT = 80
  - DEPLOY_DIR = /usr/src/truegrail-backend
branches:
  only:
  - master
language: node_js
node_js: 8.10.0
before_install:
- openssl aes-256-cbc -K $encrypted_507e586d9e43_key -iv $encrypted_507e586d9e43_iv
  -in id_rsa_travis_grail.enc -out ./id_rsa_travis_grail -d
- chmod u+x deploy.sh
after_success:
  - sudo ./deploy.sh
#- echo "running after success script"
#- eval "$(ssh-agent -s)" # start ssh-agent cache
#- chmod 600 id_rsa_travis_grail # allow read access to the private key
#- ssh-add id_rsa_travis_grail # add the private key to ssh
#
#- git config --global push.default simple # push only one branch at a time
#- git remote add deploy ssh://git@RE:$PORT$DEPLOY_DIR
#- git push deploy master
